
use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!

target '${POD_NAME}' do

  ${INCLUDED_PODS}

end

post_install do |installer|
    installer.pods_project.targets.each do |target|

        if ['StanwoodAnalytics'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
